export const characters = [
	'Annie Arelluf',
	'Elyrea',
	'Firdeso',
	'Garoto Do Sorriso',
	'Horon Aoldas',
	'Inge Naning',
	'Kapunia',
	'Lord Strikee',
	'Luther Hargreeves',
	'Marcus Eon',
	'Niix Insanity',
	'Offf Liiineee',
	'Rei Davi Benyishai',
	'The Monho',
	'Vinicius shocks',
]
